### ISSUE TITLE
(URGENT) Inkscape hangs CLI due to importing EPS forcing interactivity

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#309] opened 2023-07-26 05:54 UTC
New issue: Inkscape is forcing use of interactivity for importing EPS, and that hangs command line.

https://inkscape.org/forums/beyond/additional-question-in-inkscape-12-hangs-the-command-line-execution/

Not fixed as of two months ago: https://gitlab.com/inkscape/inkscape/-/issues/3524

A user will have to click "ok" for this to work, or else we have to modify the settings of inkspace in the Metanorma deployment, per first link:

> Hello [@AndrejMrvar](https://inkscape.org/~AndrejMrvar/), I had the same problem and was solved editing the file `/usr/share/inkscape/extensions/eps_input.inx` and replace:
> ```xml
> <param name="autorotate" type="optiongroup" appearance="combo" gui-text="Determine page orientation from text direction"
>   gui-description="The PS/EPS importer can try to determine the page orientation such that the majority of the text runs left-to-right.">
>   <option value="None">Disabled</option>
>   <option value="PageByPage">Page by page</option>
>   <option value="All">All</option>
>  </param>
> ```
> with
> ```xml
> <param name="autorotate" type="string" gui-hidden="true">None</param>
> ```

We need to do the following:
 - [ ] When we install Inkscape for our deliverables we need to ensure interactivity for Inkscape is turned off (i.e. `inkscape/extensions/eps_input.inx`)
 - [ ] When we execute EPS conversion, we need to ensure Inkscape runs without interactivity
 - [x] In our GHA jobs, we need to ensure that Inkscape has interactivity turned off. - https://github.com/metanorma/ci/pull/116

**Comment by CAMOBAP** [comment] 2023-11-14 11:48
Per the update on https://inkscape.org/forums/beyond/additional-question-in-inkscape-12-hangs-the-command-line-execution/, the issue is fixed in Inkscape 1.3.

need to verify

**Comment by CAMOBAP** [comment] 2023-11-14 13:33
The issue doesn't reproduces anymore https://github.com/metanorma/bs-202000/issues/20

**Closed by CAMOBAP** 2023-11-14 13:33 UTC
Labels: bug
