### ISSUE TITLE
action template or metanorma container change within previous ~12 days?

### ISSUE THREAD

**Issue by Kritner** [metanorma/metanorma-cli#189] opened 2020-11-17 19:36 UTC
I'm not sure if something has changed between either the GH action template we're using or the metanorma docker image, but at least within the past 12 days we're having a document fail build w/o any "code" changes to the underlying adoc information.

As an example, search "bundle exec metanorma compile draft-celi-acvp-symmetric.adoc" within "Build document in the metanorma container" step from here: https://github.com/usnistgov/ACVP/runs/1359300440?check_suite_focus=true (a successful build)

For an unsuccessful example, with no changes to the underlying adocs, search the same "bundle exec metanorma compile draft-celi-acvp-symmetric.adoc" here: https://github.com/usnistgov/ACVP/runs/1414167931?check_suite_focus=true

I don't know enough about the GH actions or how it was set up, but can follow up with @celic to get any additional info about the actions if needed.

I'm not sure if it's on our handling within our the make file, but I would have thought a build where a document couldn't be produced should fail the build; but either way it looks like something is different in the build process itself.

Let me know if there's any more information I can provide.

Thanks!

**Comment by celic** [comment] 2020-11-17 22:00
Our GitHub Actions are pulled pretty directly from https://github.com/metanorma/mn-samples-itu/blob/master/.github/workflows/docker.yml. 

When I build locally on `metanorma-cli-1.2.13.2` the document compiles. It appears that the docker container is using `metanorma-cli-1.3.8.1`. I tried `metanorma-cli-1.3.8.1` locally and compiled as well.

**Comment by ronaldtse** [comment] 2020-11-18 00:15
This may be an issue with the docker container; let me get back to you on this. Thanks for the report!

**Comment by CAMOBAP** [comment] 2020-12-01 11:48
I see that `Cannot continue processing` appears in the failed run, so this is definitely not related to docker

_Investigation in progress..._

**Comment by ronaldtse** [comment] 2020-12-01 17:53
@CAMOBAP just wanted to confirm that the metanorma-docker containers are runnable. I'm not sure if we're running into GHA issues.

**Comment by CAMOBAP** [comment] 2020-12-01 20:24
@ronaldtse @Kritner As far as I see those warnings:
```
RFC XML: Line 000529:1672 IDREF "testtypes" without matching ID
RFC XML: Line 000560:2214 IDREF "testtypes" without matching ID
RFC XML: xref target testtypes does not exist in the document
RFC XML: xref target testtypes does not exist in the document
```
Are critical

More details in *.err files

@opoudjis maybe you know, do we have some option for 'relax' validation?

**Comment by ronaldtse** [comment] 2020-12-02 14:07
@CAMOBAP can you help make a PR to metanorma/ACVP that fixes those issues? Thanks!

**Comment by CAMOBAP** [comment] 2020-12-02 14:09
@ronaldtse to be on the same page I don't know how to fix it yet, but I can dig into it, no problem

**Comment by CAMOBAP** [comment] 2020-12-06 22:07
Well... I have found so far that issue inside `asciidoctor` gem, it just 'drops' some elements (sections, lists), and if I downgrade `asciidoctor` to 2.0.10

```
gem "asciidoctor", "=2.0.10"
```

So as a short-term solution I propose to fixate this version in Gemfile. As a long-term solution, I will continue digging in `asciidoctor` gem.

**Comment by CAMOBAP** [comment] 2020-12-07 08:19
Update. 

I didn't figure out what exactly but the new version of asciidoctor just drop some nodes from output, example for https://github.com/usnistgov/ACVP/blob/master/src/draft-fussell-acvp-ecdsa.adoc it generates those XMLs:
 - [draft-fussell-acvp-ecdsa.asciidoctor-2.0.10.xml](https://github.com/metanorma/metanorma-cli/files/5651342/draft-fussell-acvp-ecdsa.asciidoctor-2.0.10.xml.txt)
 - [draft-fussell-acvp-ecdsa.rfc.asciidoctor-2.0.12.xml](https://github.com/metanorma/metanorma-cli/files/5651343/draft-fussell-acvp-ecdsa.rfc.asciidoctor-2.0.12.xml.txt)

**Comment by ronaldtse** [comment] 2020-12-07 08:22
Thanks @CAMOBAP , @opoudjis will investigate as part of metanorma/metanorma-standoc#389.

**Comment by opoudjis** [comment] 2020-12-07 10:41
One issue is indeed a newly introduced bug in Asciidoctor, as of 2.0.11, impacting lists at the end of included documents; we will freeze Asciidoctor at 2.0.10 until it is addressed. I will issue a new release of Metanorma tomorrow.

The second, which is longstanding, is that these documents contain "Terms and Definitions" sections which do not align with the expected structure of Terms and Definitions sections in Metanorma (https://www.metanorma.com/author/topics/document-format/section-terms/ : in particular, Terms and Definitions sections are expected to contain a subclause per term, and the preceding text is expected to be boilerplate.) I am introducing markup so that any ACVP sections titled as "Terms and Definitions" are not processed as Metanorma Terms and Definitions sections.

I very strongly urge you to proofread Metanorma output, and to read through https://www.metanorma.com/author/topics. Until now, the Terms and Definitions sections in ACVP have been having their content replaced with "No terms and definitions are listed in this document."

**Comment by opoudjis** [comment] 2020-12-07 10:50
@Kritner see https://github.com/metanorma/ACVP/commit/95dc5b01bdbd18d009726c12c1d98621e34e144a . You need to incorporate that one-line fix in the ACVP repository.

**Comment by Kritner** [comment] 2020-12-07 13:28
https://github.com/metanorma/metanorma-cli/issues/189#issuecomment-739839069

> @Kritner see metanorma/ACVP@95dc5b0 . You need to incorporate that one-line fix in the ACVP repository.

I tried that in [this PR](https://github.com/usnistgov/ACVP/pull/1088).  This is the resulting (failing) build (though i'm guessing is unrelated to the change from the PR): https://github.com/usnistgov/ACVP/pull/1088/checks?check_run_id=1510919667

**Comment by ronaldtse** [comment] 2020-12-07 14:06
@Kritner temporary fix sent to Kritner/ACVP#2 . @opoudjis is planning a new release tomorrow that deals with this in a more comprehensive way.

**Comment by Kritner** [comment] 2020-12-07 15:34
@ronaldtse that did in fact fix the build from the GH action, but it seems like the underlying reason for opening the issue still persists.

If you look at the produced artifacts of the build you linked https://github.com/Kritner/ACVP/pull/2/checks?check_run_id=1511121606 you'll see that several of the documents are not there, including the draft-celi-acvp-symmetric.adoc. I'll use that document as my example for the remainder of this comment.

![image](https://user-images.githubusercontent.com/8814983/101370094-0d47b900-3877-11eb-8354-02e292c908c0.png)

These are the same errors as mentioned here: https://github.com/metanorma/metanorma-cli/issues/189#issuecomment-736797913

> @ronaldtse @Kritner As far as I see those warnings:
> 
> ```
> RFC XML: Line 000529:1672 IDREF "testtypes" without matching ID
> RFC XML: Line 000560:2214 IDREF "testtypes" without matching ID
> RFC XML: xref target testtypes does not exist in the document
> RFC XML: xref target testtypes does not exist in the document
> ```
> Are critical
> 
> More details in *.err files
> 
> @opoudjis maybe you know, do we have some option for 'relax' validation?

We have both defined a `#testtypes`, as well as referenced it; I wasn't sure if the above error message was that "it was never defined but was attempted to be used" or "it was defined but never used" (though it is both defined ***and*** used in this case):

https://github.com/metanorma/ACVP/blame/FIX/tempMetanormaFix/src/symmetric/sections/04-testtypes.adoc#L2
https://github.com/metanorma/ACVP/blame/FIX/tempMetanormaFix/src/symmetric/sections/06-test-vectors.adoc#L25

**Comment by ronaldtse** [comment] 2020-12-07 16:32
@Kritner the issue with `testtypes` is not a syntax problem -- it is a regression in the parser version, which when a section ends with a list, the next section gets appended directly to the list -- effectively wiping out that next section entirely (and the anchor). This issue will be fixed in tomorrow's release where we lock to a particular version of the parser.

The GHA artifacts does not seem to reflect the requirement specified in the Gemfile, which is a bug in the workflow. I am not entirely sure why that is the case, since we already wrap the Gemfile with the special `gemfile-to-bundle-add.sh`.

Let us verify the PR tomorrow and will ping you tomorrow once it's fixed. We've dropped the ball here with this subtle bug -- it was very hard to spot. Thank you for the patience.

**Comment by ronaldtse** [comment] 2020-12-08 12:34
@Kritner we've discovered the problem -- the behavior of the Asciidoctor parser has officially changed to strip empty lines in the `include`d files, which means that any usage of `include` as a new section will require being wrapped with empty blank lines. We will be addressing this issue in a blog post.

In any case, I've updated the PR to address this issue.

**Comment by Kritner** [comment] 2020-12-08 13:29
> the behavior of the Asciidoctor parser has officially changed to strip empty lines in the included files, which means that any usage of include as a new section will require being wrapped with empty blank lines.

OK, and just to be clear you're talking specifically about changes such as this to our "root documents":

![image](https://user-images.githubusercontent.com/8814983/101489119-7dfddc80-392e-11eb-94e2-d38058775d51.png)

If I'm understanding if there were blank lines within the "included" files themselves (at the end of the files), they would be stripped out by asciidoctor, but having the blank lines in the root document for some reason aren't stripped out?

Is that because of some sort of "linting" (i don't know if that's the right word) where documents "must not end with a blank line", so if one is encountered it's removed? But blank lines are fine in between the separate `include`s within the root document?

And assuming all of the above is correct, the document generation process itself relies on these blank lines existing between "sections" (which is effectively what our separate "includes" are), and without those blank lines, the document doesn't properly parse?

And ***also*** given all of that, is there a way to return a separate status code from the build process if something like this is encountered?  We didn't realize that documents were failing to build in the GH action because the builds are passing.

-----

> We will be addressing this issue in a blog post.

Perhaps some of this is going to be detailed in the blog post you were referencing, I'll be curious to read it!

**Comment by ronaldtse** [comment] 2020-12-08 14:39
> If I'm understanding if there were blank lines within the "included" files themselves (at the end of the files), they would be stripped out by asciidoctor, but having the blank lines in the root document for some reason aren't stripped out?

Yes that's correct.

> Is that because of some sort of "linting" (i don't know if that's the right word) where documents "must not end with a blank line", so if one is encountered it's removed? But blank lines are fine in between the separate includes within the root document?

Previously asciidoctor does not "strip" blank lines at the top or bottom of the included file. But now it strips all.

> And assuming all of the above is correct, the document generation process itself relies on these blank lines existing between "sections" (which is effectively what our separate "includes" are), and without those blank lines, the document doesn't properly parse?

Correct. Blank lines need to separate the `include`s otherwise they will be considered as the same section.

> And also given all of that, is there a way to return a separate status code from the build process if something like this is encountered? We didn't realize that documents were failing to build in the GH action because the builds are passing.

I think this is mostly a "build process" issue -- whether warnings such as missing anchors should cause failure. Perhaps we need to have an option of `--strict` generation.

In addition, since there are multiple documents here in the repo, I'm not sure if a failure should halt the builds for all documents. Any suggestions?

**Comment by Kritner** [comment] 2020-12-08 15:34
> In addition, since there are multiple documents here in the repo, I'm not sure if a failure should halt the builds for all documents. Any suggestions?

Perhaps my current workflow context is important.

* Work on document `x` locally from a clone of a fork of our main repository
* Finish work on document `x`
* Build document `x` locally
* Ensure document meets expectations
* Commit changes to document `x` and push up to fork of main repository
* PR fork to main
* Wait for successful build to merge PR (at a minimum, we may wait on the timing of other moving parts to merge as well)
* After successful build, push all artifacts to github pages
  * this step is where "the problem lies", in that the "silent failure" documents were never produced, and GH pages now does not have these documents available to it.  Though this may be an issue of force pushing the `gh-pages` branch, not super familiar with the GH actions.
* If build fails, take no action on github pages

Given the above scenario, I only ever worked on document `x`, so I'm being careful about monitoring its progress.  However, in this case documents `1...n` failed to build in both our PR build as well as our "merge PR" build, without any sort of indication of said failure, and without having worked on any document in the range of `1...n`.

It would be one thing if document `x` "silently failed" to build, as we know to be wary of that document as we're actively working on it, but that's not the case here, documents that weren't touched are now "silently failing" due to a change in a dependency down stream.

Perhaps a "strict" mode or similar would work, though we have plenty of warnings we'll need to work through.  

My personal preference would be if any one document in the batch fails, even if 99% pass, the overall build is deemed a failure.  This could be on our end as well in regards to how we're doing our make file, but I haven't really looked closely into how all the pieces fit together as it relates to the make file and the github action.

**Comment by Kritner** [comment] 2021-01-26 20:10
This doesn't seem to fit into the fixes that were done on the "root" document - namely the line breaks in between includes, but we're getting that "silent failure" again on at least our symmetric document again:

https://github.com/usnistgov/ACVP/runs/1597219733?check_suite_focus=true

glancing through it says a lot of sections are missing, but I've checked a few and confirmed they should be there.  I'm not sure if it's the same issue or not, but it does circle back to my comment https://github.com/metanorma/metanorma-cli/issues/189#issuecomment-740693507

**Comment by ronaldtse** [comment] 2021-01-30 04:55
@Kritner sorry I didn’t see this message until now. Will check.

**Comment by Kritner** [comment] 2021-01-30 13:17
I think Chris ended up fixing the issue, I don't recall what it was off
hand.

Still though, would greatly appreciate some means of failing the entire
build if any one document fails to build

**Comment by CAMOBAP** [comment] 2021-03-11 16:51
@ronaldtse @Kritner is this issue still actual?

**Comment by ronaldtse** [comment] 2021-03-12 05:44
@Kritner We have added the `metanorma site generate -c metanorma.yml` (or just `metanorma site generate` if the config file name is metanorma.yml`) command to generate a full set of documents.

A single document failure will fail the site generation process. I hope this satisfies the need?

The challenge is that building of these documents work differently from Make -- the command re-generates *all* documents. 

This is because we have not (yet) implemented a similar file dependency system that allows us to only compile the changed document, and in any case Make won't know about internal dependencies (e.g. `include` dependencies within the text). This is an area we are working on.

**Comment by ronaldtse** [comment] 2021-03-12 05:46
The `metanorma site` command is described in this blog post:
https://www.metanorma.org/blog/12-19-2020/generate-mini-site-with-metanorma-cli/

**Closed** 2021-07-24 11:46 UTC
Labels: bug
