### ISSUE TITLE
metanorma site generate needs to have --agree-to-terms, etc.

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#211] opened 2021-01-16 06:28 UTC
`metanorma compile --agree-to-terms --continue-without-fonts ADOC_FILE`

These command line options should be also available in `metanorma site generate` -- we will want to install the fonts too during site generation, which also includes compilation.

I imagine we have two ways of doing so:
1. type `metanorma config --global --set font.agree_all_licenses true` and store this in `~/.metanorma/config`
2. have `metanorma site generate` accept these arguments too

Ping @CAMOBAP

**Comment by ronaldtse** [comment] 2021-01-16 06:37
This is holding up these tasks:
* https://github.com/CalConnect/iso-8601-1-amd1/pull/5
* https://github.com/metanorma/ACVP/pull/2
* https://github.com/metanorma/mn-samples-itu/runs/1694916301?check_suite_focus=true
*

**Comment by ronaldtse** [comment] 2021-01-26 00:25
@CAMOBAP is this done? Thanks.

**Comment by CAMOBAP** [comment] 2021-01-26 05:17
Done, duplicate of https://github.com/metanorma/metanorma-cli/issues/214

**Closed by CAMOBAP** 2021-01-26 05:17 UTC
Labels: enhancement
