### ISSUE TITLE
URGENT: Do not require fontist installs in running CLI specs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#213] opened 2021-01-17 03:27 UTC
From @abunashir about #212

> I'm struggling with a wired issue in our CI's, specially related to files for a specs
> It's working great locally or any other machine i've tested it to but it just kept failing in the CI and I can't possibly see the issue
> Only thing that is different in CI that it's reporting fontist can't install some fonts and I'm not sure if that's blocking file generaton or something

> Never mind, I found the solution - Looks like fontist was causing these issue
> I really think we should have some sort of configuration to bypass fontist installation for the tests and maybe we can even consider putting those together in the metanorma configuration like the errors. I spent hours dealing with this today 

Font installation can be skipped with the --continue-without-fonts CLI argument, but i don't know if there is a documented mechanism to skip it via Ruby calls...

@abunashir can you help describe how the correct behavior should be?

Ping @CAMOBAP

**Comment by abunashir** [comment] 2021-01-18 17:17
### Issues:

With the current metanora and fontist setup I can see the following issues:

* Metanorma compilation / file generation fails for missing fonts
* No staright forward way to configure this agreement from CI and tests suite.

### Expected behaviour:

Ideally, a missing a font shouldn't fail the complete file generation, maybe the output wouldn't look as pretty as it was intended but I'm not sure if it would wise to fail the complete compilation step.

Second of all, it is really great that we are making sure a user is complying with every font licences one by one, but I think we also should have a way to configure this globally for the automated system, so we our CI and test suite can easily configure those once and run smoothly.

### Possible solution:

I think we already have a `Metanorma.configure` block with main library, so maybe we can extend that to support another option for `font licences` and use that as default fallback for licence agreement.

And if we want to permanently persist this configuration in user's system, then we can also consider writing it to a metanorma config file. Here is a super old PR for some inspiration: https://github.com/riboseinc/digicert/pull/2

**Comment by CAMOBAP** [comment] 2021-01-18 17:23
@abunashir thanks for the feedback. I'm working on PR for this ticker

> I think we already have a Metanorma.configure block with main library, so maybe we can extend that to support another option for font licences and use that as default fallback for licence agreement.

Let me check this logic, but AFAIK we cannot accept font licenses by default, we must leave it for the end-users. 

From the point of view of specs, we need to pass `--continue-without-fonts`, unfortunately, I don't see a better option

> And if we want to permanently persist this configuration in user's system, then we can also consider writing it to a metanorma config file.

Yep, this is exactly what I'm working on

**Comment by CAMOBAP** [comment] 2021-01-23 12:32
https://github.com/metanorma/metanorma-cli/pull/216 - ready for review

**Comment by CAMOBAP** [comment] 2021-01-24 12:39
It's merged now. On those repos which used metanorma-cli to test: we can add extra step

```
- name: Generate metanorma config
  run: |
    docker run --rm -v ${HOME}:/hhome mikefarah/yq e '.cli.no_install_fonts = true' -i /hhome/.metanorma/config.yml
```

If there is some failing repos please let me know.

@abunashir @ronaldtse anything else supposed to be done in the scope of this task?

**Comment by ronaldtse** [comment] 2021-01-24 13:35
@CAMOBAP We shouldn't depend on `yq` anymore. Can we use `metanorma config set cli.no_install_fonts true`?

Also, we should be using the image directly instead of running docker inside GHA...?

**Comment by CAMOBAP** [comment] 2021-01-24 13:38
@ronaldtse you are right!, (OMG how can I forget about the feature which I just implemented 2 days ago??) 🤦 

For sure you can simply use `metanorma config set --global cli.no_install_fonts true

**Comment by ronaldtse** [comment] 2021-01-25 01:05
@CAMOBAP 😉 can you help apply this across the repos once @opoudjis successfully releases all gems today? Thanks.

**Comment by CAMOBAP** [comment] 2021-01-25 06:19
@ronaldtse to be on the same page this applies only to processor gems (metanorma-*), right?

**Comment by ronaldtse** [comment] 2021-01-25 06:59
I believe so. What other gems are affected by fonts?

**Comment by abunashir** [comment] 2021-01-25 16:26
Great work @CAMOBAP, I can't think of anything else apart from the one Ron mentioned, or we can also check with @opoudjis just to be double sure :) But feel free to close it once it's confirmed.

**Comment by CAMOBAP** [comment] 2021-01-27 13:29
While checking processors I have found failure for the repos:
 - https://github.com/metanorma/metanorma-iho/actions/runs/508733444 (macos)
 - https://github.com/metanorma/metanorma-un/runs/1776830046 (ubuntu & macos)
 - https://github.com/metanorma/metanorma-iec/runs/1760175273 (macos)
 - https://github.com/metanorma/metanorma-nist/runs/1760083155 (macos partially)
 - https://github.com/metanorma/metanorma-ogc/actions/runs/508660436 (macos partially)
 - https://github.com/metanorma/metanorma-m3aawg/actions/runs/508741586 (macos)

It looks like the issue isn't stable

To be updated...

**Comment by CAMOBAP** [comment] 2021-01-30 13:41
Done

**Closed by CAMOBAP** 2021-01-30 13:41 UTC
Labels: bug
